image: python:latest

before_script:
  - python --version

build:
  script:
    - python -m pip install --upgrade build
    - python -m build
  artifacts:
    paths:
      - dist/*.whl
    expire_in: 1 week
