[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
addopts = "-s --cov=p1exporter --cov-report xml --cov-report term"
testpaths = ["tests"]
